/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as MarkdownRouteImport } from './routes/markdown'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as AuthenticatedIndexRouteImport } from './routes/_authenticated/index'
import { Route as AuthCallbackRouteImport } from './routes/auth/callback'
import { Route as AuthenticatedThreadThreadIdRouteImport } from './routes/_authenticated/thread.$threadId'
import { Route as AuthenticatedThreadThreadIdWsRouteImport } from './routes/_authenticated/thread.$threadId.ws'

const MarkdownRoute = MarkdownRouteImport.update({
  id: '/markdown',
  path: '/markdown',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedIndexRoute = AuthenticatedIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthCallbackRoute = AuthCallbackRouteImport.update({
  id: '/auth/callback',
  path: '/auth/callback',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedThreadThreadIdRoute =
  AuthenticatedThreadThreadIdRouteImport.update({
    id: '/thread/$threadId',
    path: '/thread/$threadId',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedThreadThreadIdWsRoute =
  AuthenticatedThreadThreadIdWsRouteImport.update({
    id: '/ws',
    path: '/ws',
    getParentRoute: () => AuthenticatedThreadThreadIdRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof AuthenticatedIndexRoute
  '/login': typeof LoginRoute
  '/markdown': typeof MarkdownRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/thread/$threadId': typeof AuthenticatedThreadThreadIdRouteWithChildren
  '/thread/$threadId/ws': typeof AuthenticatedThreadThreadIdWsRoute
}
export interface FileRoutesByTo {
  '/login': typeof LoginRoute
  '/markdown': typeof MarkdownRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/': typeof AuthenticatedIndexRoute
  '/thread/$threadId': typeof AuthenticatedThreadThreadIdRouteWithChildren
  '/thread/$threadId/ws': typeof AuthenticatedThreadThreadIdWsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/login': typeof LoginRoute
  '/markdown': typeof MarkdownRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/_authenticated/': typeof AuthenticatedIndexRoute
  '/_authenticated/thread/$threadId': typeof AuthenticatedThreadThreadIdRouteWithChildren
  '/_authenticated/thread/$threadId/ws': typeof AuthenticatedThreadThreadIdWsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/markdown'
    | '/auth/callback'
    | '/thread/$threadId'
    | '/thread/$threadId/ws'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/login'
    | '/markdown'
    | '/auth/callback'
    | '/'
    | '/thread/$threadId'
    | '/thread/$threadId/ws'
  id:
    | '__root__'
    | '/_authenticated'
    | '/login'
    | '/markdown'
    | '/auth/callback'
    | '/_authenticated/'
    | '/_authenticated/thread/$threadId'
    | '/_authenticated/thread/$threadId/ws'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  LoginRoute: typeof LoginRoute
  MarkdownRoute: typeof MarkdownRoute
  AuthCallbackRoute: typeof AuthCallbackRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/markdown': {
      id: '/markdown'
      path: '/markdown'
      fullPath: '/markdown'
      preLoaderRoute: typeof MarkdownRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/': {
      id: '/_authenticated/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/auth/callback': {
      id: '/auth/callback'
      path: '/auth/callback'
      fullPath: '/auth/callback'
      preLoaderRoute: typeof AuthCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/thread/$threadId': {
      id: '/_authenticated/thread/$threadId'
      path: '/thread/$threadId'
      fullPath: '/thread/$threadId'
      preLoaderRoute: typeof AuthenticatedThreadThreadIdRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/thread/$threadId/ws': {
      id: '/_authenticated/thread/$threadId/ws'
      path: '/ws'
      fullPath: '/thread/$threadId/ws'
      preLoaderRoute: typeof AuthenticatedThreadThreadIdWsRouteImport
      parentRoute: typeof AuthenticatedThreadThreadIdRoute
    }
  }
}

interface AuthenticatedThreadThreadIdRouteChildren {
  AuthenticatedThreadThreadIdWsRoute: typeof AuthenticatedThreadThreadIdWsRoute
}

const AuthenticatedThreadThreadIdRouteChildren: AuthenticatedThreadThreadIdRouteChildren =
  {
    AuthenticatedThreadThreadIdWsRoute: AuthenticatedThreadThreadIdWsRoute,
  }

const AuthenticatedThreadThreadIdRouteWithChildren =
  AuthenticatedThreadThreadIdRoute._addFileChildren(
    AuthenticatedThreadThreadIdRouteChildren,
  )

interface AuthenticatedRouteChildren {
  AuthenticatedIndexRoute: typeof AuthenticatedIndexRoute
  AuthenticatedThreadThreadIdRoute: typeof AuthenticatedThreadThreadIdRouteWithChildren
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedIndexRoute: AuthenticatedIndexRoute,
  AuthenticatedThreadThreadIdRoute:
    AuthenticatedThreadThreadIdRouteWithChildren,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  LoginRoute: LoginRoute,
  MarkdownRoute: MarkdownRoute,
  AuthCallbackRoute: AuthCallbackRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
